<template>
  <CommonNavbar page="AIKit" path="Scheduler" />
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-12">
        <div class="alert alert-dismissible ai-header-alert fade show mb-4">
          This is a demo of AIKit plugin made for you to test the experience of using the plugin.

          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close">
            <span
              ><svg
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <g clip-path="url(#clip0_58_5949)">
                  <path
                    d="M10.0003 18.3337C14.6027 18.3337 18.3337 14.6027 18.3337 10.0003C18.3337 5.39795 14.6027 1.66699 10.0003 1.66699C5.39795 1.66699 1.66699 5.39795 1.66699 10.0003C1.66699 14.6027 5.39795 18.3337 10.0003 18.3337Z"
                    stroke="#FF5B5B"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                  <path
                    d="M12.5 7.5L7.5 12.5"
                    stroke="#FF5B5B"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                  <path
                    d="M7.5 7.5L12.5 12.5"
                    stroke="#FF5B5B"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </g>
                <defs>
                  <clipPath id="clip0_58_5949">
                    <rect width="20" height="20" fill="white" />
                  </clipPath>
                </defs>
              </svg>
            </span>
          </button>
        </div>
        <p>
          AIKit Scheduled AI Generators allow you to schedule content to be generated by AI. Please
          review and edit before publishing for best results. This is not a substitute for human
          editing, but a drafting aid. Happy writing!
        </p>

        <ul class="nav nav-tabs style-1 mb-4" id="pills-tab" role="tablist">
          <li class="nav-item" role="presentation">
            <RouterLink to="/auto-write" class="nav-link border-s-1">Auto Writer</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/scheduled" class="nav-link active">Scheduler</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/repurpose" class="nav-link">Repurpose</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/rss" class="nav-link">RSS</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/chatbot" class="nav-link">Chatbot</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/fine-tune-models" class="nav-link">Fine-tune Models</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/prompt" class="nav-link">AI Menu Prompts</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/setting" class="nav-link">Settings</RouterLink>
          </li>
          <li class="nav-item" role="presentation">
            <RouterLink to="/import" class="nav-link border-s-2">Export/Import Settings</RouterLink>
          </li>
        </ul>
        <div class="card h-auto">
          <div class="card-body p-0">
            <div class="table-responsive active-projects style-1">
              <table id="empoloyees-tblwrapper" class="table">
                <thead>
                  <tr>
                    <th @click="sortingArr">Description</th>
                    <th @click="sortingArr">Keywords</th>
                    <th @click="sortingArr">Status</th>
                    <th @click="sortingArr">Interval</th>
                    <th @click="sortingArr">Last generation</th>
                    <th @click="sortingArr">Next generation</th>
                    <th @click="sortingArr">Is running</th>
                    <th @click="sortingArr">Run count</th>
                    <th @click="sortingArr">Max run count</th>
                    <th @click="sortingArr">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="({ badge, title }, ind) in paginatedData" :key="ind">
                    <td class="text-black">Write RouterLink rat story</td>
                    <td>lion</td>
                    <td><span class="badge badge-success badge-sm light">Active</span></td>
                    <td>hourly</td>
                    <td>4:50 am July 11, 2023</td>
                    <td>5:50 am July 11, 2023</td>
                    <td>
                      <span :class="`badge ${badge}`">{{ title }}</span>
                    </td>
                    <td>1</td>
                    <td>5</td>
                    <td>
                      <RouterLink to="?" class="btn btn-primary light btn-sharp" v-html="editIcon">
                      </RouterLink>
                      {{ ' ' }}
                      <RouterLink to="?" class="btn btn-danger light btn-sharp" v-html="deletIcon">
                      </RouterLink>
                    </td>
                  </tr>
                </tbody>
              </table>
              <div class="d-flex align-items-center justify-content-between">
                <div class="dataTables_info">
                  Showing 1 to {{ paginatedData.length }} of 21 entries
                </div>
                <div
                  class="dataTables_paginate paging_simple_numbers"
                  id="empoloyees-tblwrapper_paginate"
                >
                  <RouterLink
                    class="paginate_button previous"
                    id="empoloyees-tblwrapper_previous"
                    @click="backPage"
                    to="?"
                    ><i class="fa-solid fa-angle-left"></i></RouterLink
                  ><span>
                    <RouterLink
                      class="paginate_button"
                      v-for="item in Math.ceil(data.length / perPage)"
                      :key="item"
                      to="?"
                      :style="`background-color:${addActive == item ? 'var(--primary);' : ''};color:${addActive == item ? '#fff !important' : ''}`"
                      @click="() => goToPage(item)"
                      >{{ item }}</RouterLink
                    >
                  </span>
                  <RouterLink
                    class="paginate_button next"
                    @click="nextPage"
                    aria-controls="empoloyees-tblwrapper"
                    data-dt-idx="3"
                    to="?"
                    tabindex="0"
                    id="empoloyees-tblwrapper_next"
                    ><i class="fa-solid fa-angle-right"></i
                  ></RouterLink>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import CommonNavbar from '../../layouts/CommonNavbar.vue'
import handlePagination from '@/layouts/HandlePaginatin'
import { schedule } from '@/elements/TableArrayData'
import { RouterLink } from 'vue-router'

export default defineComponent({
  name: 'scheduled_',
  components: { CommonNavbar, RouterLink },
  data() {
    return {
      editIcon: `<svg  width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
      deletIcon: `<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" /> <path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/><path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/><path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/></svg>`
    }
  },
  setup() {
    const handlePaginationValue = handlePagination(schedule, 10)
    return { ...handlePaginationValue }
  }
})
</script>

<style scoped>
.paginate_button {
  height: 24px;
  width: 24px;
  padding: 0;
  margin-left: 0rem;
  margin: 0 0.125rem;
  line-height: 25px;
  text-align: center;
  font-size: 13px;
  border-radius: 0.375rem;
  border: 0;
  color: #0d99ff !important;
  cursor: pointer;
  box-shadow: none;
  box-sizing: border-box;
  display: inline-block;
}

.paginate_button:hover {
  color: var(--primary);
  background: var(--rgba-primary-1);
}
.sorting {
  position: relative;
  cursor: pointer;
}
.sorting::after {
  position: absolute;
  font-family: 'Font Awesome 6 Free';
  font-weight: 900;
  background-image: none;
  margin-left: 10px;
  font-size: calc(100% - 4px);
  opacity: 0.5;
  content: '';
  background-color: red;
  width: 7px;
  height: 7px;
  clip-path: polygon(50% 0%, 0 50%, 100% 50%);
  top: 37%;
  right: 15%;
}
.sorting::before {
  position: absolute;
  font-family: 'Font Awesome 6 Free';
  font-weight: 900;
  background-image: none;
  margin-left: 10px;
  right: 15%;
  font-size: calc(100% - 4px);
  opacity: 0.5;
  content: '';
  background-color: red;
  width: 7px;
  height: 7px;
  clip-path: polygon(50% 100%, 0 50%, 100% 50%);
  top: 45%;
}
</style>
